created def validate_date_timestamp_from_something for converting tim…
sosw/sosw pull request #348
Opened 2024-09-02 12:08 UTC by JuliaRozova

created def validate_date_timestamp_from_something for converting timestamp,  added unit test for this def

2024-09-02 15:24 UTC, ngr requested changes
The logic is opposite to what we need.
Why would be implement this when there is already a `from_timestamp`?...

The idea is to receive something like: `2024-08-31 01:00:42`
And return the result of: `datetime.datetime(2024, 08, 31).timestamp()`

Means run the already existing function `validate_datetime_from_something`, then cut the hours, minutes, etc. And then return the timestamp of this transformed object.

2024-09-02 15:24 UTC, ngr commented on sosw/components/helpers.py
> +            'validate_date_timestamp_from_something',
0_о
Fix the alignment please!

2024-09-02 15:24 UTC, ngr commented on sosw/components/helpers.py
> +def validate_date_timestamp_from_something(timestamp):
Don't use the variable name `timestamp`. It will confuse with the datetime module.
And the argument is not a timestamp in most cases anyway.

2024-09-02 15:39 UTC, JuliaRozova commented
run the already existing function validate_datetime_from_something, then cut the hours, minutes, etc

Why don't use validate_date_from_something that will return exactly the date?

2024-09-02 15:49 UTC, JuliaRozova commented
Got, the object with type `date` don't have this method `timestamp`, only `datetime` object

2024-09-03 20:13 UTC, ngr requested changes

2024-09-03 20:13 UTC, ngr commented on sosw/components/helpers.py
> +    Converts the input `d` to timestamp.
>    Converts the input `d` to the timestamp of the date rounded.

2024-09-03 20:13 UTC, ngr commented on sosw/components/helpers.py
> +    :rtype: timestamp
remove the `:rtype:` please and add it to the typehint in the function declaration as `... -> float:`

2024-09-06 22:02 UTC, ngr approved these changes

2024-09-06 22:02 UTC, merged